// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {library} from '../models';
import {main} from '../models';

export function DeleteBookMetadata(arg1:string):Promise<void>;

export function GetBook(arg1:string):Promise<library.BookMetadata>;

export function GetStorageInfo():Promise<library.StorageInfo>;

export function Greet(arg1:string):Promise<string>;

export function ImportEPUB():Promise<main.ImportEPUBResult>;

export function ListBooks():Promise<Array<library.BookMetadata>>;

export function ManagedBookPath(arg1:string,arg2:string):Promise<string>;

export function SaveBookMetadata(arg1:library.BookMetadata):Promise<library.BookMetadata>;
