// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteBookMetadata(arg1) {
  return window['go']['main']['App']['DeleteBookMetadata'](arg1);
}

export function DeleteReaderNote(arg1, arg2) {
  return window['go']['main']['App']['DeleteReaderNote'](arg1, arg2);
}

export function GetBook(arg1) {
  return window['go']['main']['App']['GetBook'](arg1);
}

export function GetReaderBook(arg1) {
  return window['go']['main']['App']['GetReaderBook'](arg1);
}

export function GetStorageInfo() {
  return window['go']['main']['App']['GetStorageInfo']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportEPUB() {
  return window['go']['main']['App']['ImportEPUB']();
}

export function ListBooks() {
  return window['go']['main']['App']['ListBooks']();
}

export function ManagedBookPath(arg1, arg2) {
  return window['go']['main']['App']['ManagedBookPath'](arg1, arg2);
}

export function SaveBookMetadata(arg1) {
  return window['go']['main']['App']['SaveBookMetadata'](arg1);
}

export function SaveBookPrompt(arg1, arg2) {
  return window['go']['main']['App']['SaveBookPrompt'](arg1, arg2);
}

export function SaveReaderAppearance(arg1, arg2) {
  return window['go']['main']['App']['SaveReaderAppearance'](arg1, arg2);
}

export function SaveReaderNote(arg1, arg2) {
  return window['go']['main']['App']['SaveReaderNote'](arg1, arg2);
}

export function SaveReadingProgress(arg1, arg2) {
  return window['go']['main']['App']['SaveReadingProgress'](arg1, arg2);
}

export function SendGeminiStudyPrompt(arg1) {
  return window['go']['main']['App']['SendGeminiStudyPrompt'](arg1);
}

export function StreamGeminiStudyPrompt(arg1) {
  return window['go']['main']['App']['StreamGeminiStudyPrompt'](arg1);
}

export function TranslateSelectedText(arg1) {
  return window['go']['main']['App']['TranslateSelectedText'](arg1);
}
