// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteBookMetadata(arg1) {
  return window['go']['main']['App']['DeleteBookMetadata'](arg1);
}

export function GetBook(arg1) {
  return window['go']['main']['App']['GetBook'](arg1);
}

export function GetStorageInfo() {
  return window['go']['main']['App']['GetStorageInfo']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportEPUB() {
  return window['go']['main']['App']['ImportEPUB']();
}

export function ListBooks() {
  return window['go']['main']['App']['ListBooks']();
}

export function ManagedBookPath(arg1, arg2) {
  return window['go']['main']['App']['ManagedBookPath'](arg1, arg2);
}

export function SaveBookMetadata(arg1) {
  return window['go']['main']['App']['SaveBookMetadata'](arg1);
}
