// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {library} from '../models';
import {main} from '../models';

export function DeleteBookMetadata(arg1:string):Promise<void>;

export function DeleteReaderBookmark(arg1:string,arg2:string):Promise<library.BookMetadata>;

export function DeleteReaderNote(arg1:string,arg2:string):Promise<library.BookMetadata>;

export function GetBook(arg1:string):Promise<library.BookMetadata>;

export function GetReaderBook(arg1:string):Promise<library.ReaderBook>;

export function GetStorageInfo():Promise<library.StorageInfo>;

export function Greet(arg1:string):Promise<string>;

export function ImportEPUB():Promise<main.ImportEPUBResult>;

export function ListBooks():Promise<Array<library.BookMetadata>>;

export function ManagedBookPath(arg1:string,arg2:string):Promise<string>;

export function SaveBookMetadata(arg1:library.BookMetadata):Promise<library.BookMetadata>;

export function SaveBookPrompt(arg1:string,arg2:library.PromptConfig):Promise<library.BookMetadata>;

export function SaveReaderAppearance(arg1:string,arg2:library.ReaderAppearance):Promise<library.BookMetadata>;

export function SaveReaderBookmark(arg1:string,arg2:library.ReaderBookmark):Promise<library.BookMetadata>;

export function SaveReaderNote(arg1:string,arg2:library.ReaderNote):Promise<library.BookMetadata>;

export function SaveReadingProgress(arg1:string,arg2:library.ReadingProgress):Promise<library.BookMetadata>;

export function SendGeminiStudyPrompt(arg1:main.GeminiStudyRequest):Promise<main.GeminiStudyResponse>;

export function StreamGeminiStudyPrompt(arg1:main.GeminiStudyRequest):Promise<main.GeminiStudyResponse>;

export function TranslateSelectedText(arg1:main.GoogleTranslateRequest):Promise<main.GoogleTranslateResponse>;
